name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ current, lts/*, lts/-1 ]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js (${{ matrix.node }})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: npm ci
        run: npm ci

      - name: Validate
        run: npm run validate
